import { Device, ActivityLog, IdeUsage } from './types';

export const initialDevices: Device[] = [
  {
    id: '1',
    name: 'LD-MAC-042',
    model: 'MacBook Pro M3 Max · 64GB RAM',
    cpu: 'Apple M3 Max (16-Core)',
    ram: '64GB LPDDR5X Unified Memory',
    os: 'macOS Sequoia 15.1',
    serialNumber: 'MAC-99102-X',
    status: 'Online',
    ip: '192.168.1.104',
    lastSeen: 'Active',
    memoryUsage: '24.2 GB / 64 GB',
    memoryPercent: 37,
    ssdCapacity: '512 GB / 2048 GB',
    ssdPercent: 25,
    batteryHealth: 98,
    macAddress: 'F0:18:98:C3:FF:11',
    assetTag: '#INV-99102-DL',
    category: 'MacBook Pro',
  },
  {
    id: '2',
    name: 'LD-WIN-118',
    model: 'Lenovo ThinkPad X1 · 32GB RAM',
    cpu: 'Intel Core i7-1355U vPro',
    ram: '32GB LPDDR5 @ 5200MHz',
    os: 'Windows 11 Enterprise LTSC',
    serialNumber: 'WIN-00421-P',
    status: 'Offline',
    ip: '192.168.1.155',
    lastSeen: '2h ago',
    memoryUsage: '14.0 GB / 32 GB',
    memoryPercent: 43,
    ssdCapacity: '412 GB / 1024 GB',
    ssdPercent: 40,
    batteryHealth: 91,
    macAddress: '48:A1:C9:22:FE:1B',
    assetTag: '#INV-00421-SL',
    category: 'ThinkPad',
  },
  {
    id: '3',
    name: 'LD-MAC-009',
    model: 'MacBook Air M2 · 16GB RAM',
    cpu: 'Apple M2 (8-Core CPU / 10-Core GPU)',
    ram: '16GB Unified LPDDR5',
    os: 'macOS Sonoma 14.5',
    serialNumber: 'MAC-11234-A',
    status: 'Online',
    ip: '192.168.1.112',
    lastSeen: 'Active',
    memoryUsage: '10.0 GB / 16 GB',
    memoryPercent: 62,
    ssdCapacity: '120 GB / 512 GB',
    ssdPercent: 23,
    batteryHealth: 88,
    macAddress: 'E4:5F:01:A2:BC:6D',
    assetTag: '#INV-11234-DL',
    category: 'MacBook Pro',
  },
  {
    id: '4',
    name: 'LD-CHR-056',
    model: 'HP Chromebook 14 · 8GB RAM',
    cpu: 'Intel Celeron N4500 (Dual Core)',
    ram: '8GB LPDDR4x @ 2933MHz',
    os: 'ChromeOS Canary Channel v126',
    serialNumber: 'CHR-88210-C',
    status: 'Online',
    ip: '192.168.1.201',
    lastSeen: 'Active',
    memoryUsage: '4.2 GB / 8 GB',
    memoryPercent: 52,
    ssdCapacity: '32 GB / 128 GB',
    ssdPercent: 25,
    batteryHealth: 95,
    macAddress: 'B0:19:C2:55:EA:72',
    assetTag: '#INV-88210-CH',
    category: 'Chromebook',
  },
  {
    id: '5',
    name: 'LD-WIN-332',
    model: 'Dell XPS 15 · 32GB RAM',
    cpu: 'Intel Core i9-12900HK (14-Core)',
    ram: '32GB DDR5 @ 4800MHz',
    os: 'Microsoft Windows 11 Pro',
    serialNumber: 'CN-0GH12-8821-X99',
    status: 'Offline',
    ip: '192.168.1.142',
    lastSeen: '1d ago',
    memoryUsage: '12.4 GB / 32 GB',
    memoryPercent: 38,
    ssdCapacity: '412 GB / 1024 GB',
    ssdPercent: 40,
    batteryHealth: 94,
    macAddress: '3C:D9:2B:A1:90:7F',
    assetTag: '#INV-99283-DL',
    category: 'Dell XPS',
  },
];

export const initialAlerts: ActivityLog[] = [
  {
    id: 'a1',
    title: 'Critical Battery Drain',
    subtitle: 'High capacity variance in cell #2',
    type: 'CRITICAL',
    timestamp: '2m ago',
    deviceSN: 'MAC-99102-X',
  },
  {
    id: 'a2',
    title: 'RAM Upgrade Success',
    subtitle: 'System successfully recognized new DDR5 DIMMs',
    type: 'HEALTHY',
    timestamp: '1h ago',
    deviceSN: 'WIN-00421-P',
  },
  {
    id: 'a3',
    title: 'OS Update Pending',
    subtitle: 'KB5037853 Cumulative Security Patch ready',
    type: 'WARNING',
    timestamp: '4h ago',
    deviceSN: 'MAC-11234-A',
  },
];

export const staticIdes: IdeUsage[] = [
  { name: 'VS Code', metric: '1.2GB RAM', type: 'RAM', icon: 'code' },
  { name: 'IntelliJ IDEA', metric: '2.8GB RAM', type: 'RAM', icon: 'terminal' },
  { name: 'Docker Desktop', metric: '12% CPU', type: 'CPU', icon: 'layers' },
];
